### ISSUE TITLE
Exporting JSON snapshots keep "snapshot_file":"snap.ka" field

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KappaTools#506]
In the UI, when one requests a snapshot without specifying a name, it is named ``snap.ka`` by default.

If one exports this snapshot as a named json file (e.g. ``foo.json``), it produces a file named correctly (``foo.json``). However, that json file will contain a field ``"snapshot_file":"snap.ka"``, stating incorrectly both name and extension.

**Comment by yarden** [comment]
Is it my imagination or did ``snapshot_file`` get removed from the JSON snapshot format? I don't see it included in snapshots in recent KaSim versions (I'm using ``Kappa Simulator: v4.0.94-kappy-85-g0aafc853c``)

**Comment by pirbo** [comment]
True
