### ISSUE TITLE
odd behavior in parsing complexes from a string with kappy

### ISSUE THREAD

**Issue by yarden** [Kappa-Dev/KappaTools#624]
I'm trying to use the new features of kappy (courtesy of @hmedina) and running into some problems (I'll happily add any insights that come out of this discussion into kappy's documentation). 

I am trying to parse a complex from a string, as follows:

```
import kappy.kappa_graph as kg
# my complex, which consists of three agents: A, AToBIntegrator, and AToBRepressor
s = 'A(A_ext[1]), AToBIntegrator(site[2]), AToBRepressor(A_ext{p}[1],site[2])'  
comp = kg.KappaComplex(s) 
```

If I try to iterate through the complex, I get this:

```
for c in comp: print(c)                                                                                                                      
A
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
```

which seems odd. Is this the intended behavior?

The kind of query I'd like to answer is, e.g., whether ``'AToBIntegrator(site[_])'`` matches this complex. The answer in this case should be yes, since the complex ``'A(A_ext[1]), AToBIntegrator(site[2]), AToBRepressor(A_ext{p}[1],site[2])'`` is one in which agent ``AToBIntegrator``'s ``site`` is bound. 

I'm planning to implement this functionality - unless someone else has it already? - but wanted to check about the complex representation we have in kappy first. Thanks.

*Update*: I see that much of the relevant KaSaAn functionality (https://github.com/hmedina/KaSaAn/blob/master/KaSaAn/core/KappaComplex.py) is not in kappy. I believe the query can be answered with KaSaAn as follows:

```
from KaSaAn.core import KappaComplex         
comp = KappaComplex('A(A_ext[1]), AToBIntegrator(site[2]), AToBRepressor(A_ext{p}[1],site[2])')
# Is AToBIntegrator bound on its 'site' site?
"AToBIntegrator(site[_])" in a     
```

**Comment by pirbo** [comment]
Yes, I'll try to incorporate the functionality this afternoon :-)

**Comment by yarden** [comment]
ok, thank you very much! I wasn't trying to create more work for you, by the way... I just didn't want to step on anyone's toes if this was already in the works. Hector mentioned he will "inflate" kappy and since he's the author of this very nice code I figured it doesn't make sense for me to make a pull request without checking here first.

**Comment by hmedina** [comment]
KaSaAn's various inclusion tests do some type checking, and try to convert internally into appropriate instances. So testing a string for inclusion casts the string into a KappaAgent internally, and then operate on that. As I don't have a canonical form for complexes, just for agents, I can't perform tests against complexes, only against agents. But I can iterate over the agents of a complex, and check on those.

In KaSaAn:
```
>>> from KaSaAn.core import KappaComplex, KappaAgent
>>> yarden_complex = KappaComplex('A(A_ext[1]), AToBIntegrator(site[2]), AToBRepressor(A_ext{p}[1],site[2])')
>>> ['AToBIntegrator(site[_])' in yarden_agent for yarden_agent in yarden_complex.get_all_agents()]
[False, True, False]
```

The Python idiom of `a in b` is very intuitive, and just requires having `b`'s class have a `__contains__` method.

**Comment by yarden** [comment]
Yes, that's exactly I implemented it in my code. We'll still eventually need to deal with subcomplex matching.

**Comment by hmedina** [comment]
Yarden's example, when calling for an iterator over the KappaComplex, makes KaPy return an instance of KappaComplexIterator, which got constructed with it's `v` parameter set to whatever lurked in KappaComplex's `agent` variable, which seems to be the string used in the initializer, so it seems the returned list is just looping over every character in the initializer string (strings are iterable). Yarden's string has 72 characters, the returned list has 72 entries.

Side note, since we're using Python3.7 as a requirement, the Typing package is available, so KaPy's methods could explicitly state their types (like KaSaAn's). That way once could tell the IDE that `agents` should be of type `List[KappaAgent]` for example...

**Comment by pirbo** [comment]
KappaComplex can now be obtained from their kappa string representation thanks to the class method `from_string`.

Subcomplex matching (as well as "semantic" equality) in between complexes are now implemented. Said diffrently `in` and `==` in between 2 KappaComplex is what you expect them to be.
