### ISSUE TITLE
Using the KaSim API as a dependency

### ISSUE THREAD

**Issue by jonathan-laurent** [Kappa-Dev/KappaTools#633]
As a result of this [issue](https://github.com/jonathan-laurent/kappa-counterfactuals/issues/1), I am trying to update the code for counterfactual resimulation.

However, I am stuck at the very beginning when I am trying to write a dune file listing `kappa-library` as a dependency. I successfully did `opam install kappa-library` but then if I write the following dune file:

```
(library
  (name resimulation)
  (libraries kappa-library))
```

I get the following message from dune:

```
Error: Library "kappa-library" not found.
```

I get the same error with `kappa_library`, `Kappa_library`, `kappa_runtime`...

DOes anyone have some directions on how to use KaSim as a dependency in an OCaml project?

**Comment by hmedina** [comment]
From my dusty notes on how to get TQL up and running:

```
For KaSim:
opam pin add kappa-library git+https://github.com/Kappa-Dev/KaSim.git
opam pin add kappa-binaries git+https://github.com/Kappa-Dev/KaSim.git
For WebSim:
opam pin add kappa-agents git+https://github.com/Kappa-Dev/KaSim.git
opam pin add kappa-server git+https://github.com/Kappa-Dev/KaSim.git
```

You may need to update the path, as the repo is not called KaSim anymore, but KappaTools

**Comment by jonathan-laurent** [comment]
I did the above, but then dune does not recognize `kappa-library` as an existing library.

**Comment by hmedina** [comment]
Maybe some of the debugging steps done here can help?

https://github.com/ocaml/dune/issues/1873

**Comment by jonathan-laurent** [comment]
Thanks Hector, this actually solved my problem.

Running `dune installed-libraries` suggested that I fix my dune file as follows:

```
(library
  (name resimulation)
  (libraries kappa-library.generic kappa-library.runtime kappa-library.terms))
```
