### ISSUE TITLE
"make all" issue for KappaTools-4.1beta (following successful opam pin add --dev KaSim)

### ISSUE THREAD

**Issue by JeffEdge** [Kappa-Dev/KappaTools#635]
Hi all,
I proceeded with: "opam pin add --dev KaSim" for KappaTools-4.1beta, no issue.
The problem starts with "make all"
1) Had to change "Pervasive..." to "Stdlib__pervasive..." : seems to work
2) then ran into the following:

dune build --only-packages kappa-library,kappa-binaries
File "KaSa_rep/counting_enumerating_species/counting_print.ml", line 42, characters 18-42:
42 |           let _ = Printf.fprintf log "%i*" in
                       ^^^^^^^^^^^^^^^^^^^^^^^^
Error (warning 5): this function application is partial,
maybe some arguments are missing.
File "cflow/blackboard_generation.ml", line 2788, characters 20-74:
2788 |             let _ = print_preblackboard parameter handler error blackboard in ()
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error (warning 5): this function application is partial,
maybe some arguments are missing.
make: *** [Makefile:120: all] Error 1

Could someone help?
I have the following installed:
angstrom           0.15.0      
astring            0.8.5       
base-bigarray      base
base-bytes         base        
base-threads       base
base-unix          base
base64             3.5.0       
bigarray-compat    1.0.0       
bigstringaf        0.7.0       
biniou             1.2.1       
bos                0.2.0       
carton             0.4.0       
carton-git         0.4.0       
carton-lwt         0.4.0       
checkseum          0.3.1       
cmdliner           1.0.4       
conf-pkg-config    2          
cppo               1.6.7       
csexp              1.4.0       
cstruct            6.0.0       
decompress         1.3.0       
digestif           1.0.0       
domain-name        0.3.0       
duff               0.4         
dune               2.8.4       
dune-configurator  2.8.4       
easy-format        1.3.2     
emile              1.1         
encore             0.8         
eqaf               0.7         
fmt                0.8.9       
fpath              0.7.3       
git                3.3.3       
hmap               0.8.1       
hxd                0.3.1       
ipaddr             5.0.1       
ke                 0.4         
logs               0.7.0       
lwt                5.4.0       
macaddr            5.0.1       
mimic              0.0.1       
mirage-flow        2.0.1       
mmap               1.1.0       
num                1.4      
ocaml              4.08.1      
ocaml-config       1           
ocaml-syntax-shims 1.0.0       
ocaml-system       4.08.1      
ocamlbuild         0.14.0  
ocamlfind          1.9.1       
ocamlgraph         2.0.0       
ocplib-endian      1.1    
opam-depext        1.1.5       
optint             0.0.5       
pecu               0.5         
psq                0.2.0       
re                 1.9.0       
result             1.5         
rresult            0.6.0       
seq                base  
stdlib-shims       0.3.0       
stringext          1.6.0       
topkg              1.0.3       
uchar              0.0.2       
uri                4.1.0       
uutf               1.0.2       
yojson             1.7.0       

and I use WSL2 Ubuntu 20.04
Any help, suggestion would be most welcome as I really would like to get this to run :-)
Many thanks and best wishes!

**Comment by hmedina** [comment]
Hi Jeff,

I just tried and got it working, though not the way I got it working under 16.04. Since the ppa for Opam appears to be broken for Ubuntu 20.04, and compiling from source gave me too many "deprecation" errors [!!], I used the APT versions. It even got the bubblewrap component to not issue cryptic errors all over the place. Here is the condensed version of what I did, on a Windows-Store-fresh install of Ubuntu 20.04:

```
[sudo] apt update ; apt upgrade
[sudo] apt get m4 gcc libgmp-dev pkg-config ocaml opam
opam init
eval $(opam env)
opam pin add kappa-library git+https://github.com/Kappa-Dev/KappaTools.git
opam pin add kappa-binaries git+https://github.com/Kappa-Dev/KappaTools.git
opam pin add kappa-agents git+https://github.com/Kappa-Dev/KappaTools.git
opam pin add kappa-server git+https://github.com/Kappa-Dev/KappaTools.git
```

The last two pins are to get WebSim up and running; if you only want KaSim you can omit them. Running Ubuntu Focal Fossa 20.04, on WSL2. Hope that helps!

**Comment by JeffEdge** [comment]
Hi Hector,
Worked perfectly!
Thanks!
