### ISSUE TITLE
Kappapp frozen?

### ISSUE THREAD

**Issue by hmedina** [Kappa-Dev/KappaTools#642]
Since source is failing on my system (#641 ), I download the latest available Kappapp version, from September 2020. On Windows, double-clicking the executable opens the Electron window, but core functionality is broken or hidden:

a) Can't open or import a kappa file
b) Can't type into the text box
c) If the layout is the same as KaSim-in-browser, the bottom of the app does not show the Run, or Pause criteria box
d) New project does not produce any visible change in the app

![image](https://user-images.githubusercontent.com/1588553/159074979-db99deef-424c-4b48-a2a3-1360d82d78f9.png)
(same behavior when going full screen)

**Comment by feret** [comment]
Hi Hector, 

I am not sure I can help. 
 -> I have access to no Windows machine 
 -> Travis can no longer be used to test multi-OS settings (it is not free anymore and I find the monthly fee very high). 
 -> I know almost nothin about the UI and the app deployment. 


Yet, on the website I see versions of the app for May 2021. 
(https://tools.kappalanguage.org/nightly-builds/)

Do I look in the good place ? 

Cheers. 
Jérôme.

**Comment by hmedina** [comment]
Hi Jérôme,

I was using the latest release build, at
https://github.com/Kappa-Dev/KappaTools/releases

Testing the May 2021 version has the same behavior as the September 2020 version on my machine.

Since you fixed #641 , I got the from-source compilation working, so I do not need the app; do not worry about my use-case.

Going forward, it may be desirable to adopt a different IDE approach; BNGL is using a Visual Studio Code extension, and that program is free & available cross-platform. Hacking functionality for it is also not too cumbersome, with ad-hoc end-user workflows being straightforward.

Side note:
For the nightly link, the SSL certificate expired several months ago: "The certificate for tools.kappalanguage.org expired on 8/19/2021"

**Comment by feret** [comment]
@hmedina Do you still have the issue ? 
@pirbo has corrected a garbage collection issue with new versions of the ocsygen library. 
It it likely to have solved your issue. Let me know.

**Comment by hmedina** [comment]
KappApp behavior has not changed. Nightly link has valid SSL certificate.

Side note: I suggest renaming the Windows build to something that says "Windows", rather than just "KappaBin.zip"

**Comment by antoinepouille** [comment]
I suspect that it is what I fixed recently in https://github.com/Kappa-Dev/KappaTools/commit/9169bdb5ecbb055ef81e1e08bbc6433c78d0ae27 

Windows electron was broken because of a bad `file:///` url parsing. I tested it since and the whole app was working correctly. 

I'm closing this, but let me know if you can test it from a recent nightly build https://tools.kappalanguage.org/nightly-builds/

**Comment by hmedina** [comment]
I tested today's nightly build, and it seems to be fully working. Ran a toy model, viewed a snapshot in patchwork & ball-and-link modes, and the behavior was as expected.

**Comment by antoinepouille** [comment]
@hmedina 

Perfect! thanks for testing :-)
