### ISSUE TITLE
Add wheels for kappy for Python 3.10 on PyPI

### ISSUE THREAD

**Issue by bgyori** [Kappa-Dev/KappaTools#652]
It would be great if manylinux / macosx whl files for Python 3.10 could be uploaded to PyPI for kappy version 4.1.2 (https://pypi.org/project/kappy/4.1.2/#files). Let me know if I can help somehow!

**Comment by hmedina** [comment]
Along the way, we can also drop support for no-longer maintained Pythons 3.6, 3.5, and 2.7

**Comment by bgyori** [comment]
Hello, this would still be important for making kappy be installable on Python 3.10. If there is no one who has the bandwidth to do this, I'd be happy to try as long as someone can add me as a maintainer on the PyPI project for kappy (https://pypi.org/project/kappy). Thanks!

**Comment by hmedina** [comment]
Ok, I'm now a co-owner of the kappy project on PyPI; Ben I believe you have also been invited, correct?

**Comment by pirbo** [comment]
(Sorry for how long it took me to see the notifications :facepalm:)

**Comment by bgyori** [comment]
Got it, thanks! I'll attempt to add Python 3.10 wheels.

**Comment by feret** [comment]
Hi, 
Would it be possible to be added as maintainer as well ? 
Matthieu Bouguéon will have a research engineer position next year, and he will likely works on this. 
Best. 
Jérôme.

**Comment by feret** [comment]
Sure, thank you ! 

------
Jérôme Feret
Chargé de recherche dans l'équipe Antique 
Professeur attaché PSL 
DI-ENS
45 rue d’Ulm 
75005 Paris, France 
+33 (0)1 44 32 37 66

---
Pour une évaluation indépendante, transparente et rigoureuse !
Je soutiens la Commission d'Évaluation de l'Inria.

**Comment by bgyori** [comment]
I added some new wheels for Python 3.10 for both Mac and Linux and these work in my test installs, so I'll close this issue.
